
"""
Main GUI for SPotS.

Main window was generated by calling:
    pyuic4 main_window.ui > main_window.py
    
Created on Sat Oct 18 17:09:11 2014

@author: Christian Wichmann
"""


import logging
from PyQt4 import QtGui
from PyQt4 import QtCore

from main_window import Ui_MainWindow

from spots import plc


__all__ = ['start_gui']


logger = logging.getLogger('spots.gui')


APP_NAME = 'SPotS'


class SpotsGui(QtGui.QMainWindow, Ui_MainWindow):
    """Main window for SPotS"""
    def __init__(self, parent=None):
        """Initialize main window for SPotS."""
        logger.info('Building main window of SPotS...')
        QtGui.QMainWindow.__init__(self, parent)
        self.setupUi(self)
        # set internal state variables
        self.current_output_image = dict()
        self.current_input_image = dict()
        # line number and character offset for last error or an empty tuple if
        # no error is currently present
        self.current_error_coordinates = tuple()
        # build main window
        self.setup_widgets()
        self.center_on_screen()
        self.set_signals_and_slots()
        self.setup_plc_timer()

    def setup_widgets(self):
        self.highlighter = IecStHighlighter(self.source_code_editor.document())

    def center_on_screen(self):
        """Centers the window on the screen."""
        screen = QtGui.QDesktopWidget().screenGeometry()
        size = self.geometry()
        self.move((screen.width() - size.width()) / 2,
                  (screen.height() - size.height()) / 2)

    def set_signals_and_slots(self):
        """Sets all signals and slots for main window."""
        self.actionQuit.triggered.connect(QtGui.qApp.quit)
        self.execute_button.clicked.connect(self.on_execute_button)

    def setup_plc_timer(self):
        self.timer = QtCore.QTimer()
        #self.timer

    @QtCore.pyqtSlot()
    def on_execute_button(self):
        try:
            self.current_input_image = plc.read_input_bits()
            self.current_output_image = plc.process_input_to_output(str(self.source_code_editor.toPlainText()),
                                                                    self.current_input_image)
            plc.write_output_bits(self.current_output_image)
        except SyntaxError as e:
            self.error_message_label.setText('{} on character {} in line {}'.format(e.message, e.offset, e.lineno))
            self.current_error_coordinates = (e.lineno, e.offset)
            return
        except KeyError as e:
            self.error_message_label.setText('Unknown input/output used: {}'.format(e.message))
            return
        self.error_message_label.setText('')
        self.update_inputs_and_outputs()

    def update_inputs_and_outputs(self):
        input_string = ''
        for k, v in sorted(self.current_input_image.iteritems()):
            input_string += '{:<5}: \t{}\n'.format(k, v)
        self.input_text_edit.setText(input_string)
        output_string = ''
        for k, v in sorted(self.current_output_image.iteritems()):
            output_string += '{:<5}: \t{}\n'.format(k, v)
        self.output_text_edit.setText(output_string)


class IecStHighlighter(QtGui.QSyntaxHighlighter):
    """Provides syntac highlighting for IEC 61131-3 ST source code. Only some
    of the syntax is currently supported!

    Code of this class stolen from pyQt example file!
    """
    def __init__(self, parent=None):
        super(IecStHighlighter, self).__init__(parent)

        keywordFormat = QtGui.QTextCharFormat()
        keywordFormat.setForeground(QtCore.Qt.darkBlue)
        keywordFormat.setFontWeight(QtGui.QFont.Bold)

        keywordPatterns = ["\\btrue\\b", "\\bfalse\\b", "\\band\\b",
                           "\\bor\\b", "\\bnot\\b"]

        self.highlightingRules = [(QtCore.QRegExp(pattern), keywordFormat)
                for pattern in keywordPatterns]

        input_format = QtGui.QTextCharFormat()
        input_format.setFontWeight(QtGui.QFont.Bold)
        input_format.setForeground(QtCore.Qt.red)
        self.highlightingRules.append((QtCore.QRegExp("[I][0-9]+"),
                input_format))

        output_format = QtGui.QTextCharFormat()
        output_format.setFontWeight(QtGui.QFont.Bold)
        output_format.setForeground(QtCore.Qt.blue)
        self.highlightingRules.append((QtCore.QRegExp("[O][0-9]+"),
                output_format))

        singleLineCommentFormat = QtGui.QTextCharFormat()
        singleLineCommentFormat.setForeground(QtCore.Qt.green)
        self.highlightingRules.append((QtCore.QRegExp("//[^\n]*"),
                singleLineCommentFormat))

        self.multiLineCommentFormat = QtGui.QTextCharFormat()
        self.multiLineCommentFormat.setForeground(QtCore.Qt.green)

        quotationFormat = QtGui.QTextCharFormat()
        quotationFormat.setForeground(QtCore.Qt.darkGreen)
        self.highlightingRules.append((QtCore.QRegExp("\".*\""),
                quotationFormat))

        functionFormat = QtGui.QTextCharFormat()
        functionFormat.setFontItalic(True)
        functionFormat.setForeground(QtCore.Qt.blue)
        self.highlightingRules.append((QtCore.QRegExp("\\b[A-Za-z0-9_]+(?=\\()"),
                functionFormat))

        #self.commentStartExpression = QtCore.QRegExp("(\\*")
        #self.commentEndExpression = QtCore.QRegExp("\\*)")
        self.commentStartExpression = QtCore.QRegExp("\(\\*")
        self.commentEndExpression = QtCore.QRegExp("\\*\)")

    def highlightBlock(self, text):
        for pattern, format in self.highlightingRules:
            expression = QtCore.QRegExp(pattern)
            index = expression.indexIn(text)
            while index >= 0:
                length = expression.matchedLength()
                self.setFormat(index, length, format)
                index = expression.indexIn(text, index + length)

        self.setCurrentBlockState(0)

        startIndex = 0
        if self.previousBlockState() != 1:
            startIndex = self.commentStartExpression.indexIn(text)

        while startIndex >= 0:
            endIndex = self.commentEndExpression.indexIn(text, startIndex)

            if endIndex == -1:
                self.setCurrentBlockState(1)
                commentLength = len(text) - startIndex
            else:
                commentLength = endIndex - startIndex + self.commentEndExpression.matchedLength()

            self.setFormat(startIndex, commentLength,
                    self.multiLineCommentFormat)
            startIndex = self.commentStartExpression.indexIn(text,
                    startIndex + commentLength);


def start_gui():
    import sys

    app = QtGui.QApplication(sys.argv)
    app.setApplicationName(APP_NAME)

    main = SpotsGui()
    main.show()

    sys.exit(app.exec_())


if __name__ == "__main__":
    start_gui()
